name: Build CLI assets
description: Build CLI assets from source

inputs:
  working-directory:
    description: Where to run
    required: false
    default: cli

runs:
  using: "composite"
  steps:
    - name: Build cli-app
      shell: bash
      working-directory: "./upstream/packages/cli-app"
      run: |
        npx pnpm i
        npx pnpm run cli-app:build
